/console_replay:
  ros__parameters:
    data_file_name: 'console_data_complete_7.bin'
    output_mode: UDP
    ros_topic_name: /itp_commands
    start_type_description_service: true
    udp_ip: 127.0.0.1
    udp_port: 5001
    use_sim_time: false

